### ISSUE TITLE
Create: projectID element always ends up as child of the first variant name

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#51]
Setup:

Add 2 separate variant elements (not nameParts).  For each, attach a projectID. Therefore, each variant element should have one descendant projectID.

The actual outcome, both projectID elements are descendants of the first variant element and the second has no descendant projectID

related to issue #40

**Comment by ilovan** [comment]
It seems to be working now. 
I am getting:

    <identity>
            <preferredForm>
                <namePart partType="given">Mihaela</namePart>
                <namePart partType="family">Ilovan</namePart>
            </preferredForm>
            <variantForms>
                <variant>
                    <namePart partType="given">Mihaela</namePart>
                    <namePart partType="family">Mihalachi</namePart>
                    <variantType>birthName</variantType>
                    <authorizedBy>
                        <projectId>ceww</projectId>
                    </authorizedBy>
                </variant>
                <variant>
                    <namePart partType="termsOfAddress">The Great Inquisitor</namePart>
                    <variantType>nickname</variantType>
                    <authorizedBy>
                        <projectId>canwwr</projectId>
                    </authorizedBy>
                </variant>
            </variantForms>
        </identity>
