### ISSUE TITLE
Conceptual shortcoming: path not properly represented in the model

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#53]
Given 2 specific names where the first name is represented by first XPath below and the second name by the second XPath: 

/a/b/c/variant[0]/namePart
/a/b/c//variant[1]/namePart

The dialogues do not consider the index and treat both as: /a/b/c/varient/namePart.

The result is that the 2 namePart elements are added to the first variant element because the index is ignored.  The second variant element disappears.  This occurs when the edit dialogue loads the XML into the underlying model and renders the form elements.

Likely the root cause of  #40 #51 #52.  Specific examples can be found in those issues.

**Comment by ilovan** [comment]
I think you did it, @jefferya. I'll let you have the honours of closing this one.
