### ISSUE TITLE
Editing: @partType attribute not rendered in form

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#54]
Editing a person with a partType attribute - the attribute is not rendered in the form nor is it retained when the form saved.

**Comment by jefferya** [comment]
Seems to be working on Chrome and IE.  Firefox is having issue on my computer.  Also, existing entities ingested into the dev server use a different set of partType values relative to latest set of values.

**Comment by brundin** [comment]
Right -- the partType values were changed so that they parallel the values
used in the MODS schema, i.e., "family" and "given".  So all ingested
entities should be using the "family" and "given" values, and new entities
should also be using these values.

MRB

**Comment by ilovan** [comment]
Works in both Firefox and Chrome.
