### ISSUE TITLE
accessCondition element text needs to be changed from 3.0 to 4.0 in cD.js

### ISSUE THREAD

**Issue by brundin** [cwrc/CWRC-Dialogs#56]
In the cD.js file, the variable accessConditionText, which appears in two different places within two different functions, addRecordInfo and addModsInfo, needs to have its text changed from 3.0 references to 4.0 references.

So, change this

var accessConditionText = 'Use of this public-domain resource is governed by the <a href="http://creativecommons.org/licenses/by-nc/3.0/" rel="license">Creative Commons Attribution-NonCommercial 3.0 Unported License</a>.';

to this

var accessConditionText = 'Use of this public-domain resource is governed by the <a href="http://creativecommons.org/licenses/by-nc/4.0/" rel="license">Creative Commons Attribution-NonCommercial 4.0 International License</a>.';

**Comment by ilovan** [comment]
new entities: 4.0
