### ISSUE TITLE
originInfo/projectId element out of order, so newly created entities do not validate

### ISSUE THREAD

**Issue by brundin** [cwrc/CWRC-Dialogs#57]
For person, organization, and place entities that are created using the CWRC dialogs, the originInfo/projectId element is created in the wrong sequential order, so newly created entities do not validate.  In the entities.rng schema, the originInfo element defines the following child elements in this sequential order: projectId, recordIdentifier, recordCreationDate, recordChangeDate, and recordOrigin.  However, new entities that are created using the CWRC dialogs create the following child elements of originInfo in this order: recordCreationDate, recordChangeDate, and projectId.  I.e., projectId is appearing last, as opposed to first, as the schema defines these elements.  Thus, newly created entities using the CWRC dialogs are not validating, due to this error.

So, we can either (a) modify the dialogs so that projectId appears first, or (b) modify the entities.rng schema such that the order of the child elements of originInfo does not matter, by wrapping all of the child elements of originInfo in an interleave directive.

I recommend option (b), that we just make that small change in the entities.rng schema.

**Comment by susanirenebrown** [comment]
I agree with the modification to the schema.

On Wed, Jan 28, 2015 at 11:28 AM, brundin <notifications@github.com> wrote:

> For person, organization, and place entities that are created using the
> CWRC dialogs, the originInfo/projectId element is created in the wrong
> sequential order, so newly created entities do not validate. In the
> entities.rng schema, the originInfo element defines the following child
> elements in this sequential order: projectId, recordIdentifier,
> recordCreationDate, recordChangeDate, and recordOrigin. However, new
> entities that are created using the CWRC dialogs create the following child
> elements of originInfo in this order: recordCreationDate, recordChangeDate,
> and projectId. I.e., projectId is appearing last, as opposed to first, as
> the schema defines these elements. Thus, newly created entities using the
> CWRC dialogs are not validating, due to this error.
>
> So, we can either (a) modify the dialogs so that projectId appears first,
> or (b) modify the entities.rng schema such that the order of the child
> elements of originInfo does not matter, by wrapping all of the child
> elements of originInfo in an interleave directive.
>
> I recommend option (b), that we just make that small change in the
> entities.rng schema.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/CWRC-Dialogs/issues/57>.
>



-- 
____________________________________________________________________________

____________________________________________________________________________

Susan Brown
Director, Orlando Project; Project Leader, Canadian Writing Research
Collaboratory
Visiting Professor                                      Professor
English and Film Studies                           School of English and
Theatre Studies
University of Alberta                                  University of Guelph
Edmonton, Alberta T6G 2E5                      Guelph, Ontario N1G 2W1
Canada
780-862-0155                                            519-824-4120 x53266
(office)
                                                               519-766-0844
(fax)
susan.brown@ualberta.ca                         sbrown@uoguelph.ca

**Comment by brundin** [comment]
MRB & JCA have made the change.  Closed.
