### ISSUE TITLE
"edit" & "select" buttons should not be clickable unless an item is selected in the search result listing

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#59]
If a user search for a entity and a list of results is returned, a user can 'click' the 'edit' button without selecting a entity from the list and no error or notification is displayed leaving the user to wonder why the dialog is empty.

The 'edit' button should be in a disabled state or a notification triggered if the user has not selected an item to edit.

Same thing with the 'select' button

**Comment by ilovan** [comment]
Desired enhancements:
* all entities: disable "select" and "edit" in the search pop-up unless a search result is selected first
* organization and place: add "create new" as an option in the search pop-up
* title: remove "edit"  (@brundin , please correct me if  I am wrong, but from your last description of the desired title entity behaviour, we don't want a "create new " option on the title search pop-up, or do we?)

**Comment by brundin** [comment]
I had originally being thinking "no," we didn't want a to use the dialogs
to create a new title entity (MODS record), but Jeff pointed out the
following logical scenario:

* can use the title entity dialog to create more minimal title entities
(MODS records), including other resource types such as audio, video, etc.
* would use the MODS XML Form Builder forms to create fuller title entities
(MODS records), and we will eventually have forms for other resource types,
such as audio, video, etc.
* the MODS XML Form Builder forms will be used for all edits of title
entities (MODS records).

So, yes we can use the title entity dialog form to create more
skeletal/minimal title entities (MODS records).

MRB
