### ISSUE TITLE
Source XML entity on multiple lines then not rendered correctly in the interface

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#61]
For example, using pre-existing entities the second and subsequent "namepart" element don't display on the interface.

**Comment by susanirenebrown** [comment]
sigh….

On February 13, 2015 at 6:31:35 PM, Jeffery Antoniuk (notifications@github.com) wrote:

For example, using pre-existing entities the second and subsequent "namepart" element don't display on the interface.

**Comment by ilovan** [comment]
fixed
