### ISSUE TITLE
Firefox: attribute values not being added to interface

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Dialogs#62]

**Comment by ilovan** [comment]
Interface of the creation/edit dialogue or the result area at http://cwrc-dev-01.srv.ualberta.ca/dev/CWRC-Dialogs/? 

They both work fine for me
![image](https://cloud.githubusercontent.com/assets/6600070/6323777/369be4ec-baed-11e4-8b81-eaf577eb5731.png)
