### ISSUE TITLE
Add namePart @type value for full name - Western order (not recommended)

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Dialogs#66]
about naming conventions: http://en.wikipedia.org/wiki/Personal_name#Name_order

**Comment by brundin** [comment]
Missed the link to the Wikipedia entry, and just noticed it now after I made the fix.  Thanks for including it!  We can change/alter the terms we are using.  Went with "inverted order" and "direct order", following the terminology used in the Library of Congress' MODS top level elements guidelines: http://www.loc.gov/standards/mods/userguide/name.html#displayform

MRZB

**Comment by ilovan** [comment]
That's probably for the best. 
Thanks
